project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!index_old.qmd"
    - "!cv_ivar_old.qmd"
    - "!cv.qmd"
    - "!notes/mscfe_wqu.qmd"
    - "!mscfe-wqu/*.qmd"
    - "!blog/*.qmd"
    - "!notes/**/*.qmd"
    # - "!portfolio.qmd"

website:
  title: "Ivar Soares Urdalen - Financial Data"
  open-graph: true
  site-url: https://ivarurdalen.github.io
  repo-url: https://www.github.com/ivarurdalen/ivarurdalen.github.io
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: overlay
  page-footer: 
    left: |
      Website made with [Quarto](https://www.quarto.org)
  navbar:
    # background: light
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv_ivar.qmd
      # - text: "Notes" 
      #   file: notes/index.qmd
      - text: "Portfolio"
        file: site/portfolio/index.qmd
      # - text: "Blog"
      #   file: site/blog/index.qmd

    right: 
      - icon: github
        href: https://github.com/ivarurdalen/ivarurdalen.github.io
      # - href: portfolio.qmd
      # - href: mscfe_wqu.qmd
      #   text: MSc FE WQU
      # - href: blog.qmd
  
  sidebar: 
    # - id: notes
    - title: "Notes"
      style: "floating"
      collapse-level: 2
      align: left
      contents: 
        # - text: "Notes"
          # href: notes/index.qmd
        - notes/index.qmd
        - section: "Algorithmic Trading"
          contents:
            - notes/trading/index.qmd
            - notes/trading/strategies.qmd
        - section: "Databases"
          contents:
            - notes/databases/sql.qmd
            - notes/databases/financial-database.qmd
    
    - title: "Portfolio"
      contents: 
        - site/portfolio/index.qmd

    # - title: "Blog"
    #   contents: 
    #     - site/blog/index.qmd

  
format:
  html:
    theme: cosmo
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    toc-title: "Contents"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


