---
title: "CV"
---

I am currently looking to transition from working as a Civil Engineer to Data Science and Data Engineering.

### Key Qualifications

### Technologies
Here is a list of technologies I consider myself sufficiently proficient to apply these in projects.
However, I believe that a developer should always be ready to pick up new skills and learn new technology.

**Languages:** Python, JavaScript  
**Databases:** PostgreSQL  
**Frameworks:** FastAPI  
**Other skills:** Cloud computing, containers using Docker, source control with Git

### Online Courses

::: {.d-flex .justify-content-between}
::: {}
[Machine Learning (Stanford, Coursera)](files/machine-learning.pdf)
:::
::: {.text-end}
2012
:::
:::

::: {.d-flex .justify-content-between}
::: {}
[Computer for Data Analysis (John Hopkins, Coursera)](files/computing-for-data-analysis.pdf)
:::
::: {.text-end}
2013
:::
:::

::: {.d-flex .justify-content-between}
::: {}
[Data Analysis and Statistical Inference (Duke, Coursera)](https://www.coursera.org/account/accomplishments/records/QTWF8YK53Z)
:::
::: {.text-end}
2014
:::
:::

### Work Experience

::: {.d-flex .justify-content-between}
::: {}
**[Ramboll Norway](https://no.ramboll.com/)**  
:::
::: {.text-end}
Aug 2017 - Nov 2022
:::
:::
*Senior Consulting Civil and Environmental Engineer*

- Leading consulting projects for water engineering (pipelines, pumping stations, treatment plants, stormwater design, etc.)
- Typically having the Discipline Lead role in projects 
- Tasks: Producing tender documents, reports, design review, project management, BIM/CAD design.
- Example of IT project: Assisting in deploying prototype for project QA with Python web app (Flask framework)

::: {.d-flex .justify-content-between}
::: {}
**[Aqua Unique Norway](https://aquaunique.no/)**  
:::
::: {.text-end}
08.2015 - 07.2027
:::
:::
*Project Manager*

- Task: Technical design in project, project management, contracts, supplier negotiations, marketing, strategy and recruitment.
- Development of Excel spreadsheets for project budgets, pricing models, supplier comparison, technical design, etc.
- Assisting with operation of IT infrastructure (website, email, file server, backup, wiki, CRM system, etc)

::: {.d-flex .justify-content-between}
::: {}
**[Asplan Viak](http://www.asplanviak.no)**  
:::
::: {.text-end}
Aug 2014 - Sept 2015
:::
:::
*Consulting Civil Engineer*

- Tasks: Water and wastewater treatment plant desig and BIM/CAD modelling. Material takeoff, P&ID, tender documents.

::: {.d-flex .justify-content-between}
::: {}
**[COWI](http://www.cowi.com)**  
:::
::: {.text-end}
Summer 2012
:::
:::
*Summer Intern*

- Design of water distribution systems, and CAD modelling.

::: {.d-flex .justify-content-between}
::: {}
**[Silicon Labs](https://www.silabs.com/)**  (formerly Energy Micro)
:::
::: {.text-end}
Summer 2009
:::
:::
*Summer Intern*

- C programming for development kit for energy efficient microcontroller.


### Education

::: {.d-flex .justify-content-between}
::: {}
**[MSc in Financial Engineering](https://www.wqu.edu/programs/mscfe/)**  
*World Quant University*
:::
::: {.text-end}
Online
Started 2022
:::
:::
- Courses: Financial Markets, Financial Data, Financial Econometrics
- Heavy focus on using Python and its capabilities for data and statistical analysis

::: {.d-flex .justify-content-between}
::: {}
**MSc in Civil and Environmental Engineering**  
*Norwegian University of Science and Technology (NTNU)*  
Average Grade: A
:::
::: {.text-end}
Trondheim, Norway
June 2015
:::
:::
- Specialization: Water and Wastewater Engineering
- Additional courses in Computer Science and Finance.

::: {.d-flex .justify-content-between}
::: {}

**MSc Student exchange**  
*Federal University of Santa Catarina*
:::
::: {.text-end}
Florianópolis, Brazil  
2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
**Spanish and Portuguese language studies**  
Self studies while traveling
:::
::: {.text-end}
South America  
2013
:::
:::

::: {.d-flex .justify-content-between}
::: {}
**Technical Cybernetics**  
*Norwegian University of Science and Technology (NTNU)*  
Grade (1st yr): A
:::
::: {.text-end}
Trondheim, Norway  
2008 - 2009
:::
:::

### Awards

#### Winner of [Norwegian Informatics Olympiad](http://www.nio.no) for High School Students
::: {.d-flex .justify-content-between}
::: {}
Algorithmic Programming Competition for High School Students (C++ Programming)
Participated in Baltic Informatics Olympiad (BOI) and International Olympiad in Informatics (IOI).
:::
::: {.text-end}
2007
:::
:::

### Languages

::: {.d-flex .justify-content-between}
::: {}
Portuguese, English and Norwegian
:::
::: {.text-end}
Speak and write fluently
:::
:::

::: {.d-flex .justify-content-between}
::: {}
Spanish
:::
::: {.text-end}
Good understanding
:::
:::